version: '3'

services:
  postgres:
    image: postgres
  web:
    build: .
    volumes:
      - .:/codebase
    ports:
      - "1337:80"
    depends_on:
      - postgres
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=donationteam@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=donationteam
