# Generated by Django 2.1.1 on 2018-09-30 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_management', '0002_auto_20180930_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='group_management.Event'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.BooleanField(verbose_name='Status'),
        ),
    ]
